### PR TITLE
Add Card.friendly_brand and ExpDate.mmyy

### PR DESCRIPTION
**Pull request by joshkel**

### CODE REVIEW

**Comment by orokusaki** [comment]
@joshkel Great work, thanks for the patch!

**Comment by orokusaki** [comment]
@joshkel I added a new release tag https://github.com/orokusaki/pycard/releases

**Comment by joshkel** [comment]
Thanks!

**Comment by joshkel** [comment]
It looks like the internal version number is still 0.9.5, even though the release tag is 0.9.6?

**Comment by orokusaki** [comment]
@joshkel good catch; I did this quickly at break earlier. I just created v0.9.7.

**Comment by joshkel** [comment]
Thank you.

**Pull request merged**
